language: c

dist: bionic

script: make test

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0; export CFLAGS=-fsanitize=undefined"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env:
         - MATRIX_EVAL="CC=gcc-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env:
        - MATRIX_EVAL="CC=gcc-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7; export CFLAGS=-fsanitize=undefined"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7-i686-linux-gnu
            - gcc-7-multilib-i686-linux-gnu
      env:
        - MATRIX_EVAL="CC=i686-linux-gnu-gcc-7; export LDFLAGS=-static"

before_install:
    - eval "${MATRIX_EVAL}"
