name: Benchmark (new)

on: [push, pull_request_target, workflow_dispatch]

jobs:
  benchmark-new:
    name: Performance regression check (new)
    if: contains(toJSON(github.event.head_commit.message), 'Merge pull request ') == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install-dependencies
        run: |
            sudo pip3 install numpy
            sudo apt install libsdl2-dev libsdl2-mixer-dev
        shell: bash
      - name: default build
        run: make
      - name: Run benchmark
        run: |
          tests/bench-aggregator.py
      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmarks
          tool: 'customBiggerIsBetter'
          output-file-path: benchmark_output.json
          github-token: ${{ secrets.RV32EMU_BENCH_TOKEN }}
          gh-repository: 'github.com/sysprog21/rv32emu-bench'
          gh-pages-branch: 'master'
          auto-push: true
          comment-always: true
          benchmark-data-dir-path: .
